backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "index.html"
        label: "Strona główna"
        name: "home"
        fields:
          - { label: "Treść", name: "body", widget: "markdown" }
